Cura/Cura/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('web/', include('web.urls')),
    path('', include('web.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Cura/web/urls.py
from django.urls import include, path
from .views import *
from django.conf.urls import include, url
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views
app_name = 'web'
urlpatterns = [
	path('', Datos.as_view()),
    path('datos/', Datos.as_view(), name='datos'),
    path('subirCSV2/', SubirCSV2.as_view(), name="subirCSV2"),
    path('paginar/', Paginar.as_view(), name="paginar"),
]

Cura/web/forms.py
from django import forms
from .models import *

class CrmForm(forms.ModelForm):
    class Meta:
       model = Crm
       fields = ('d_codigo', 'd_asenta','d_tipo_asenta', 'D_mnpio', 'd_estado', 'd_ciudad', 'd_CP',
        		'c_estado', 'c_oficina', 'c_CP', 'c_tipo_asenta', 'c_mnpio', 'id_asenta_cpcons', 'd_zona', 'c_cve_ciudad',)
       widgets = {
             'd_codigo': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'d_codigo', 'id':'d_codigo_cr'}),
             'd_asenta': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'d_asenta', 'id':'d_asenta_cr'}),
             'd_tipo_asenta': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'d_tipo_asenta', 'id':'d_tipo_asenta_cr'}),
             'D_mnpio': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'D_mnpio', 'id':'D_mnpio_cr'}),
             'd_estado': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'d_estado', 'id':'d_estado_cr'}),
             'd_ciudad': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'d_ciudad', 'id':'d_ciudad_cr'}),
             'd_CP': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'d_CP', 'id':'d_CP_cr'}),
             'c_estado': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'c_estado', 'id':'c_estado_cr'}),
             'c_oficina': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'c_oficina', 'id':'c_oficina_cr'}),
             'c_CP': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'c_CP', 'id':'c_CP_cr'}),
             'c_tipo_asenta': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'c_tipo_asenta', 'id':'c_tipo_asenta_cr'}),
             'c_mnpio': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'c_mnpio', 'id':'c_mnpio_cr'}),
             'id_asenta_cpcons': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'id_asenta_cpcons', 'id':'id_asenta_cpcons_cr'}),
             'd_zona': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'d_zona', 'id':'d_zona_cr'}),
             'c_cve_ciudad': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'c_cve_ciudad', 'id':'c_cve_ciudad_cr'}),
        }
class CrmFormModal(forms.ModelForm):
    class Meta:
       model = Crm
       fields = ('d_codigo', 'd_asenta','d_tipo_asenta', 'D_mnpio', 'd_estado', 'd_ciudad', 'd_CP',
        		'c_estado', 'c_oficina', 'c_CP', 'c_tipo_asenta', 'c_mnpio', 'id_asenta_cpcons', 'd_zona', 'c_cve_ciudad',)
       widgets = {
             'd_codigo': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'d_codigo', 'id':'d_codigo_cr1'}),
             'd_asenta': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'d_asenta', 'id':'d_asenta_cr1'}),
             'd_tipo_asenta': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'d_tipo_asenta', 'id':'d_tipo_asenta_cr1'}),
             'D_mnpio': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'D_mnpio', 'id':'D_mnpio_cr1'}),
             'd_estado': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'d_estado', 'id':'d_estado_cr1'}),
             'd_ciudad': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'d_ciudad', 'id':'d_ciudad_cr1'}),
             'd_CP': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'d_CP', 'id':'d_CP_cr1'}),
             'c_estado': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'c_estado', 'id':'c_estado_cr1'}),
             'c_oficina': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'c_oficina', 'id':'c_oficina_cr1'}),
             'c_CP': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'c_CP', 'id':'c_CP_cr1'}),
             'c_tipo_asenta': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'c_tipo_asenta', 'id':'c_tipo_asenta_cr1'}),
             'c_mnpio': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'c_mnpio', 'id':'c_mnpio_cr1'}),
             'id_asenta_cpcons': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'id_asenta_cpcons', 'id':'id_asenta_cpcons_cr1'}),
             'd_zona': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'d_zona', 'id':'d_zona_cr1'}),
             'c_cve_ciudad': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'c_cve_ciudad', 'id':'c_cve_ciudad_cr1'}),
        }
        
class CSVForm(forms.Form):
    archivo = forms.FileField(widget = forms.FileInput(attrs = {'class' : 'form-control'}))

Cura/web/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>CRM</title>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>

</head>
<body>
	
</body>

</html>

Cura/web/templates/main/datos.html
{% load staticfiles %}
{% block title %}
<title>CRM</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>

{% endblock title %}
<!-- Latest compiled and minified CSS -->


<!-- Optional theme -->
<!-- Latest compiled and minified JavaScript -->
{%  block content %}
  <form method="POST">
  {% csrf_token %}
  <div class="col-md-12">
  <div class="col-xs-10 col-md-10"></div>
  <div class="col-xs-10 col-md-10">
    <input type="text" class="form-control bg-light border-0 small" placeholder="Buscar..." name="buscar" value="{{ request.POST.buscar }}">
</div>
    <div class="col-xs-2 col-md-2">
      <button class="btn btn-primary" type="submit" align="left">
        <i>GO</i>
      </button>
    </div>
</div>
</form>


          <div class=" row" style="margin: 0px;">
              <div class="col-md-4 col-sm-4 col-xs-12 col-md-offset-4">
                <form method="POST" enctype="multipart/form-data" action="{% url 'web:subirCSV2' %}">
                    <legend class="mi-form-legend">Archivo csv</legend>
               {% csrf_token %}
          {{ excelform.archivo }}
          <input type="file" name="archivo" class="form-control" required="" id="id_archivo">
          <button type="submit" class="btn btn-info">Guardar</button>
          </form>
          <div class="form-group" style="padding-top: 20px;">
          </div>
          </div>
          </div>
<table class="table" id="tableNoticias">
    <thead style="background-color: #ebebeb; margin: 0px; font-size: 13px; text-align: center">
        <tr>
            <th class="text-center">d_codigo</th>
            <th class="text-center">d_asenta</th>
            <th class="text-center">d_tipo_asenta</th>
            <th class="text-center">D_mnpio</th>
            <th class="text-center">d_estado</th>
            <th class="text-center">d_ciudad</th>
            <th class="text-center">d_CP</th>
            <th class="text-center">c_estado</th>
            <th class="text-center">c_oficina</th>
            <th class="text-center">c_CP</th>
            <th class="text-center">c_tipo_asenta</th>
            <th class="text-center">c_mnpio</th>
            <th class="text-center">id_asenta_cpcons</th>
            <th class="text-center">d_zona</th>
            <th class="text-center">c_cve_ciudad</th>
        </tr>
    </thead>
    <tbody style="background: white; margin: 0px; font-size: 11px; text-align: center">
        {% if crm %}
        {% for crm in crm %}
        <tr>
            <td style="vertical-align : middle;">
                {{crm.d_codigo}}
            </td>
            <td style="vertical-align : middle;">
                {{crm.d_asenta}}
            </td>
            <td style="vertical-align : middle;">
                {{crm.d_tipo_asenta}}
            </td>
            <td style="vertical-align : middle;">
                {{crm.D_mnpio}}
            </td>
            <td style="vertical-align : middle;">
                {{crm.d_estado}}
            </td>
            <td style="vertical-align : middle;">
                {{crm.d_ciudad}}
            </td>
            <td style="vertical-align : middle;">
                {{crm.d_CP}}
            </td>
             <td style="vertical-align : middle;">
                {{crm.c_estado}}
            </td>
            <td style="vertical-align : middle;">
                {{crm.c_oficina}}
            </td>
            <td style="vertical-align : middle;">
                {{crm.c_CP}}
            </td>
            <td style="vertical-align : middle;">
                {{crm.c_tipo_asenta}}
            </td>
            <td style="vertical-align : middle;">
                {{crm.c_mnpio}}
            </td>
            <td style="vertical-align : middle;">
                {{crm.id_asenta_cpcons}}
            </td>
            <td style="vertical-align : middle;">
                {{crm.d_zona}}
            </td>
             <td style="vertical-align : middle;">
                {{crm.c_cve_ciudad}}

            </td>

        </tr>
        {% endfor %}

        {% else %}
        <h1>No hay registros</h1>

        {% endif %}
    </tbody>

</table>

{% endblock %}